server:
  port: 9010
logging:
  level:
    org:
      springframework: info
spring:
  datasource:
    emismobile:
      jdbcUrl: jdbc:oracle:thin:@xxx
      username: XXX
      password: XXX
      driver-class-name: oracle.jdbc.driver.OracleDriver
service:
  access-token:
    secret: 'f$Gaj39ANkY&8W^4wzz9i6@Pq7$qJRz2Lbe&W9VZVWd'
    issuer: 'booking-main'
    subject: 'booking-fe'
    expiration-in-minutes: 15
  refresh-token:
    secret: 'F&5L*wiywz45EtkbUap&bQcWHDMbDqQe3M@j294C7L1'
    issuer: 'booking-main'
    subject: 'booking-fe'
    expiration-in-minutes: 30
