server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: none
            default_schema: DEFAULT
        database: oracle
    h2:
        console:
            enabled: 'true'
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@fei-sql3.upceucebny.cz:1521:BDAS
        username: st67263
        password: abcde
